version: '3.8'
services:
  ai-agent:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./reports:/app/reports
      - ./memory:/app/memory
    environment:
      - PYTHONUNBUFFERED=1